name: earnipay_interview
description: Earnipay Mobile Engineering Code Test
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.8.4
  flutter_staggered_animations: ^1.1.1
  dio: ^5.2.0+1
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  http_mock_adapter: ^0.4.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/png/icon.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/png/icon.png